### ISSUE TITLE
How to make it work with normal image links

### ISSUE THREAD

**Issue by john-cj** [funkjunky/mdfigcaption#3]
Hi! Thanks for this plugin.

I tried to change default regex from

    /~\[([^\]]*)\]\(([^\)]*)\)/

to

    /!\[([^\]]*)\]\(([^\)]*)\)/

In other words, I just changed `~` to `!`, to make it work with normal images links, like this one:

    ![foo bar](http://...)

But for some reason, after I changed `~` to `!` in regex, captions are no longer shown. Any ideas why? Thanks.

**Comment by TheFive** [comment]
I assume, because the standard interpretation of ![]() has higher priority than this plugin.
You can check my assumption, by having a look at the result of the console.log in line 8 of this plugin. If - after your change - this log does not log anything, you cant overwrite standard behavior with this simple regex mechanism.
